import './style.scss';
import '@carbon/web-components/es/components/button/index';
import '@carbon/web-components/es/components/ui-shell/index';
import '@carbon/web-components/es/components/breadcrumb/index';
import '@carbon/web-components/es/components/tabs/index';
import '@carbon/web-components/es/components/data-table/index.js';
import '@carbon/web-components/es/components/link/index';
import '@carbon/web-components/es/components/pagination/index';
import './components';
